"""Add ownership columns

Revision ID: 54b065a855c0
Revises: e1ebe1c5755f
Create Date: 2026-09-08 19:57:35.678117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b065a855c0'
down_revision: Union[str, None] = 'e1ebe1c5755f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'properties', 'users', ['owner_id'], ['id'])
    op.add_column('tenants', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tenants', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'user_id')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'owner_id')
    # ### end Alembic commands ###
